### ISSUE TITLE
Parser: Node types & parse logic

### ISSUE THREAD

**Issue by tk-codes** [bazo-blockchain/lazo#10]
Continue from the branch `parser`: https://github.com/bazo-blockchain/lazo/tree/parser

**Comment by skas102** [comment]
Implemented:
* TypeNode
* VariableNode
* parseType
* parseVariable

**Comment by tk-codes** [comment]
The following nodes are implemented in the first version.

- ProgramNode
- ContractNode
- FunctionNode
- VariableNode
- TypeNode
- IfStatementNode
- ReturnStatementNode
- AssignmentStatementNode
- BinaryExpressionNode
- UnaryExpression
- DesignatorNode
- IntegerLiteralNode
- StringLiteralNode
- CharacterLiteralNode
- BoolLiteralNode
- ErrorNode
