### ISSUE TITLE
Refactor Compiler

### ISSUE THREAD

**Issue by tk-codes** [bazo-blockchain/lazo#21]
- Packagedoc: Write comments for exported functions / types/ variables (See https://goreportcard.com/report/github.com/bazo-blockchain/lazo)
- Fix inefficient assignment
- Integrate go linter
- Rename *_test_util.go* to *_util_test.go*
- Move to Go modules for dependency management
- Remove Getter functions
- Packaging (more cohersion, export as less as possible)
- Remove cmd (move cobra cli commands to cli package)
- Fix String() functions (check nil and write custom string represention)

**Comment by rpfister102** [comment]
Packagedoc: Write comments for exported functions / types/ variables (See https://goreportcard.com/report/github.com/bazo-blockchain/lazo)
Fix inefficient assignment DONE
Integrate go linter DONE
Rename _test_util.go to _util_test.go
Move to Go modules for dependency management
Remove Getter functions DONE
Packaging (more cohersion, export as less as possible)
Remove cmd (move cobra cli commands to cli package)
Fix String() functions (check nil and write custom string represention)
