### ISSUE TITLE
Struct

### ISSUE THREAD

**Issue by skas102** [bazo-blockchain/lazo#45]
Structs should be supported.

Struct Declaration:
```cs
struct Person {
 string name
 int balance
}
```

Struct Creation:
```cs
new Person()
new Person("test", 120)
new Person(name="test", balance=120)
```

Struct Usage:
```cs
Person p = new Person()
p.name = "test"           // Assignment using member access designator
string name = p.name // Read value using member access expression
```

**Comment by skas102** [comment]
This story also includes:
* Testing of member access in the generator

**Comment by skas102** [comment]
Wir können das Problem folgendermassen lösen:

- Auf jedem Struct gibt es ein zusätzliches Property: is_default welches mit True initialisiert wird. Sobald dass Struct zugewiesen wird wird dieses Property auf false gesetzt. Der Benutzer kann dann dieses Property abfragen.

Everytime an uninitialized property is accessed, we initialize it before accessing it e.g. 
```
struct Person {
  name: string // default ""
  age: int  // default 0
  father: Person. // nil until accessed
}

p = new Person() // name = "", age = 0, father = nil
p.name = "Max"
p.father.name = "Maximilian" -> Initialize father with the Default Person Struct when accessing it for the first time.
```

**Comment by tk-codes** [comment]
Done. Default struct initialization should be implemented in VM (https://github.com/bazo-blockchain/bazo-vm/issues/38)
