### ISSUE TITLE
Allow only literal expressions for contract state variable declaration

### ISSUE THREAD

**Issue by tk-codes** [bazo-blockchain/lazo#60]
Initially, only the following literal expressions are allowed with variable declaration:
* IntegerLiteral
* BooleanLiteral
* CharacterLiteral
* StringLiteral

```cs
contract MyContract {
  int x = 5         
  bool b = true 
  char c = 'c'
  String s = "hello"
}
```

All the other expressions are not allowed. They are only allowed inside the constructor/function.
Some semantic errors are shown below. See page 54 of [Lazo Specification](https://github.com/bazo-blockchain/lazo-specification) for the complete list of expressions.
```cs
contract MyContract {
  int x = 5 + 5      // ERROR: Binary expressions
  int y = x          // ERROR: designator expressions
  int z = calc(x, y) // ERROR: function calls
}
```

**Comment by skas102** [comment]
Entweder alles zulassen oder garnicht.

**Comment by tk-codes** [comment]
Decision: All expressions are supported
